WITH item_ids AS (
{{VITAL_ITEM_IDS_SUBQUERY}}
)
SELECT
    CE.ICUSTAY_ID,
    CE.CHARTTIME,
    CE.ITEMID,
    CE.VALUENUM
FROM
    CHARTEVENTS CE
INNER JOIN item_ids ii ON
    CE.ITEMID = ii.ITEMID
INNER JOIN ICUSTAYS ie ON
    CE.ICUSTAY_ID = ie.ICUSTAY_ID
WHERE
    CE.VALUENUM IS NOT NULL
    AND (CE.`ERROR` IS NULL
        OR CE.`ERROR` = 0)
    AND CE.CHARTTIME >= ie.INTIME
    AND CE.CHARTTIME < DATE_ADD(ie.INTIME, INTERVAL 1 DAY);
