  SELECT
    x.SUBJECT_ID,
    x.HADM_ID,
    x.ICUSTAY_ID,
    x.INTIME,
    x.OUTTIME,
    x.FIRST_CAREUNIT,
    x.GENDER,
    x.AGE,
    x.HOSPITAL_EXPIRE_FLAG
  FROM (
    SELECT
      ICU.SUBJECT_ID,
      ICU.HADM_ID,
      ICU.ICUSTAY_ID,
      ICU.INTIME,
      ICU.OUTTIME,
      ICU.FIRST_CAREUNIT,
      PAT.GENDER,
      FLOOR(DATEDIFF(ICU.INTIME, PAT.DOB) / 365.2425) AS AGE,
      ADM.HOSPITAL_EXPIRE_FLAG,
      ROW_NUMBER() OVER (PARTITION BY ICU.SUBJECT_ID ORDER BY ICU.INTIME) AS RN
    FROM ICUSTAYS ICU
    JOIN ADMISSIONS ADM ON ICU.HADM_ID = ADM.HADM_ID
    JOIN PATIENTS PAT ON ICU.SUBJECT_ID = PAT.SUBJECT_ID
  ) x
  WHERE x.RN = 1
    AND x.AGE BETWEEN 18 AND 89;